# Define project language
language: objective-c

# Update Git Submodules
before_install:
  - git submodule update --init --recursive
  
# Travis CI automatically runs pod install during the install phase,
# so we don't have to do anything else to setup the project deps.
 
# Undocumented flag to specify the SDK to build for and avoid code sign errors
# Required until the default script for objective-c handles this automatically
# @see https://github.com/travis-ci/travis-build/pull/109
xcode_sdk: iphonesimulator